const{getStore}=require("@netlify/blobs"),lazy=require("./anime-lazy-mapping.js");
const LAZY_STORE="anime-lazy-resolution",MAPPING_URL=process.env.ANIME_MAPPING_URL||"https://anikoto-nuvio.netlify.app/.netlify/functions/anime-mapping",TMDB_KEY=process.env.TMDB_API_KEY||"68e094699525b18a70bab2f86b1fa706",CACHE_TTL=300000,REQUEST_TIMEOUT=3500;
const cache=new Map(),inflight=new Map();
function log(x){console.log(`[SHARED MAPPING] ${x}`)}
function store(){return getStore({name:LAZY_STORE,siteID:process.env.NETLIFY_SITE_ID,token:process.env.NETLIFY_AUTH_TOKEN})}
function valid(m){if(!m||typeof m!=="object")return false;const mal=String(m.mal_id||m.malId||"").trim(),ep=Number(m.mal_episode||m.target_episode||m.episode||0);return/^\d+$/.test(mal)&&Number(mal)>0&&Number.isInteger(ep)&&ep>0}
function normalize(m,source){if(!valid(m))return null;return{...m,mal_id:String(m.mal_id||m.malId),mal_episode:Number(m.mal_episode||m.target_episode||m.episode),source:source||m.source||"shared"}}
async function fetchJson(url,timeout=REQUEST_TIMEOUT){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{Accept:"application/json","User-Agent":"AniKoto-Nuvio-Shared-Mapping/2.0"},signal:c.signal});if(!r.ok)return null;return await r.json()}catch(e){return null}finally{clearTimeout(t)}}
async function dbLookup(id,s,e){try{const r=await store().get(`anime:${id}`,{type:"json"}),x=r&&r.seasons&&r.seasons[String(s)],v=x&&x.episodes&&x.episodes[String(e)];if(v&&Number(v.mal_episode)>0){const m={tmdb_id:id,imdb_id:r.imdb_id||null,mal_id:r.mal_id||null,anime_title:r.title||"",titles:r.titles||[],season:Number(s),episode:Number(e),mal_episode:Number(v.mal_episode),air_date:v.air_date||"",season_title:x.title||"",source:"lazy-db"};return valid(m)?m:null}}catch(e){}return null}
async function lazyResolve(id,s,e){const m=await lazy.resolveMapping(id,s,e);return normalize(m,"lazy-resolver")}
async function normalResolve(id,s,e){const u=`${MAPPING_URL}?tmdbId=${encodeURIComponent(id)}&season=${encodeURIComponent(s)}&episode=${encodeURIComponent(e)}`,d=await fetchJson(u,REQUEST_TIMEOUT);return d&&d.ok?normalize(d.mapping,"normal-mapper"):null}
async function tvMapping(id,s,e){const key=`tv:${id}:${s}:${e}`,hit=cache.get(key);if(hit&&hit.expires>Date.now())return hit.value;const running=inflight.get(key);if(running)return running;const p=(async()=>{log(`REQUEST TMDB=${id} S${s}E${e}`);const db=await dbLookup(id,s,e);if(db){log(`LAZY DB HIT TMDB=${id} S${s}E${e}`);cache.set(key,{value:db,expires:Date.now()+CACHE_TTL});return db}log(`LAZY DB MISS TMDB=${id} S${s}E${e}`);const lm=await lazyResolve(id,s,e);if(lm){log(`LAZY RESOLVED TMDB=${id} S${s}E${e} -> MAL=${lm.mal_id} E${lm.mal_episode}`);cache.set(key,{value:lm,expires:Date.now()+CACHE_TTL});return lm}const normal=await normalResolve(id,s,e);if(normal){log(`NORMAL MAPPER HIT TMDB=${id} S${s}E${e} -> MAL=${normal.mal_id} E${normal.mal_episode}`);cache.set(key,{value:normal,expires:Date.now()+CACHE_TTL});return normal}log(`MISS TMDB=${id} S${s}E${e}`);return null})().finally(()=>inflight.delete(key));inflight.set(key,p);return p}
function movieKey(id){return String(id||"").trim()}
async function movieLookup(id){try{const r=await store().get(`anime:${id}`,{type:"json"}),m=r&&r.movies&&r.movies[movieKey(id)];if(valid(m)){log(`MOVIE HIT TMDB=${id}`);return m}}catch(e){}return null}
async function tmdbExternal(id){return fetchJson(`https://api.themoviedb.org/3/movie/${encodeURIComponent(id)}/external_ids?api_key=${encodeURIComponent(TMDB_KEY)}`,2500)}
async function aniByTmdb(id,imdb){return fetchJson(imdb?`https://api.ani.zip/mappings?themoviedb_id=${encodeURIComponent(id)}&imdb_id=${encodeURIComponent(imdb)}`:`https://api.ani.zip/mappings?themoviedb_id=${encodeURIComponent(id)}`,2500)}
async function aniByMal(mal){return fetchJson(`https://api.ani.zip/mappings?mal_id=${encodeURIComponent(mal)}`,2500)}
async function arm(id,imdb){const urls=[imdb?`https://arm.haglund.dev/api/v2/imdb?id=${encodeURIComponent(imdb)}`:null,`https://arm.haglund.dev/api/v2/themoviedb?id=${encodeURIComponent(id)}`].filter(Boolean),rs=await Promise.allSettled(urls.map(u=>fetchJson(u,2200))),ids=[];for(const r of rs)if(r.status==="fulfilled"&&Array.isArray(r.value))for(const x of r.value||[])if(x&&x.myanimelist)ids.push(String(x.myanimelist));return[...new Set(ids)]}
function validAnimeMeta(ani,mal){if(!ani||typeof ani!=="object"||!ani.mappings)return false;if(String(ani.mappings.mal_id||mal)!==String(mal))return false;if(ani.type&&!["tv","movie","ona","ova","special","music"].includes(String(ani.type).toLowerCase()))return false;return!!(ani.title||ani.titles||ani.episodes||ani.anime)}
function movieRecord(id,imdb,mal,ani,raw){const titles=[];if(ani&&ani.title)titles.push(ani.title);if(ani&&ani.title_english)titles.push(ani.title_english);if(ani&&ani.title_japanese)titles.push(ani.title_japanese);if(ani&&ani.titles&&typeof ani.titles==="object")titles.push(...Object.values(ani.titles).map(x=>typeof x==="string"?x:x&&x.title).filter(Boolean));return{tmdb_id:String(id),imdb_id:imdb||null,mal_id:String(mal),mal_episode:1,anime_title:String(ani&&ani.title||raw&&raw.title||titles[0]||""),titles:[...new Set(titles.map(String).filter(Boolean))].slice(0,50),source:"movie"}}
async function validateMovieCandidate(id,imdb,mal,raw){const n=String(mal||"").trim();if(!/^\d+$/.test(n)||Number(n)<1)return null;const ani=await aniByMal(n);return validAnimeMeta(ani,n)?movieRecord(id,imdb,n,ani,raw):null}
async function resolveMovie(id){const old=await movieLookup(id);if(old)return old;const ext=await tmdbExternal(id),imdb=ext&&ext.imdb_id?String(ext.imdb_id):null;const[a,arms]=await Promise.all([aniByTmdb(id,imdb),arm(id,imdb)]),candidates=[];if(a&&a.mappings&&a.mappings.mal_id)candidates.push(String(a.mappings.mal_id));candidates.push(...arms);const unique=[...new Set(candidates)],results=await Promise.allSettled(unique.map(m=>validateMovieCandidate(id,imdb,m,a&&a.mappings)));const found=results.map(r=>r.status==="fulfilled"?r.value:null).find(Boolean);if(!found){log(`MISS TMDB=${id}`);return null}try{const s=store(),r=await s.get(`anime:${id}`,{type:"json"}),next={...(r||{tmdb_id:String(id),imdb_id:imdb,seasons:{},movies:{},population:{}}),tmdb_id:String(id),imdb_id:(r&&r.imdb_id)||imdb,movies:{...((r&&r.movies)||{}),[movieKey(id)]:found},updatedAt:Date.now()};await s.setJSON(`anime:${id}`,next)}catch(e){log(`MOVIE WRITE FAILED TMDB=${id}: ${e.message}`)}log(`MOVIE RESOLVED TMDB=${id} -> MAL=${found.mal_id}`);return found}
async function getMapping({tmdbId,mediaType="tv",season=1,episode=1}){const id=String(tmdbId||"").trim(),type=String(mediaType||"tv").toLowerCase(),s=Number(season)||1,e=Number(episode)||1;if(!id)return null;return type==="movie"?resolveMovie(id):tvMapping(id,s,e)}
exports.handler=async event=>{const p=event.queryStringParameters||{},id=String(p.tmdbId||p.tmdb_id||"").trim(),type=String(p.mediaType||p.type||"tv").toLowerCase(),s=Number(p.season)||1,e=Number(p.episode)||1;if((event.httpMethod||"GET").toUpperCase()==="OPTIONS")return{statusCode:204,headers:{"Access-Control-Allow-Origin":"*"}};if(!id)return{statusCode:400,body:JSON.stringify({ok:false,error:"tmdbId required"})};try{const m=await getMapping({tmdbId:id,mediaType:type,season:s,episode:e});if(m)return{statusCode:200,headers:{"Content-Type":"application/json","Cache-Control":"public,max-age=30,s-maxage=300,stale-while-revalidate=60","Access-Control-Allow-Origin":"*"},body:JSON.stringify({ok:true,source:m.source,mapping:m})};return{statusCode:404,headers:{"Content-Type":"application/json","Cache-Control":"no-store","Access-Control-Allow-Origin":"*"},body:JSON.stringify({ok:false,mapping:null})}}catch(e){console.error("[SHARED MAPPING] FATAL",e);return{statusCode:500,headers:{"Content-Type":"application/json","Cache-Control":"no-store","Access-Control-Allow-Origin":"*"},body:JSON.stringify({ok:false,error:e.message||"Mapping service error"})}}};
exports.getMapping=getMapping;
