[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/anime-mapping"
  to = "/.netlify/functions/anime-lazy-mapping"
  status = 200

[functions."anime-mapping-updater"]
  schedule = "@weekly"
