/* AniKoto Nuvio provider: optimized, cached, parallel extraction. */
const ANIKOTO_URL="https://anikototv.to",AJAX_URL=ANIKOTO_URL+"/ajax",MAPPER_URL="https://mapper.nekostream.site",MAPPING_URL="https://anikoto-nuvio.netlify.app/.netlify/functions/shared-mapping",UA="Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/AD1A.240418.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.54 Mobile Safari/537.36",HEADERS={"Referer":ANIKOTO_URL+"/","X-Requested-With":"XMLHttpRequest","User-Agent":UA},TIMEOUT=15000;
function log(x){console.log("[AniKoto] "+x)}
class NuvioTTLCache{constructor(){this.m=new Map()}get(k){const x=this.m.get(k);if(!x)return;if(x.e<=Date.now()){this.m.delete(k);return}return x.v}set(k,v,ttl){this.m.set(k,{v,e:Date.now()+ttl});return v}delete(k){this.m.delete(k)}}
const CACHE=globalThis.__NUVIO_PROVIDER_CACHE__||(globalThis.__NUVIO_PROVIDER_CACHE__=new NuvioTTLCache());
const MAP_TTL=86400000,SERVER_TTL=3600000,STREAM_TTL=1800000,EXTRACT_TIMEOUT=4500;
async function memo(key,ttl,fn){const hit=CACHE.get(key);if(hit!==undefined)return hit;const p=Promise.resolve().then(fn);CACHE.set(key,p,ttl);try{const v=await p;CACHE.set(key,v,ttl);return v}catch(e){CACHE.delete(key);throw e}}
async function timeout(p,ms=EXTRACT_TIMEOUT){let t;try{return await Promise.race([p,new Promise((_,r)=>t=setTimeout(()=>r(new Error("timeout")),ms))])}finally{clearTimeout(t)}}
async function settled(tasks,ms=EXTRACT_TIMEOUT){const r=await Promise.allSettled(tasks.map(x=>timeout(Promise.resolve().then(x),ms)));return r.filter(x=>x.status==="fulfilled").map(x=>x.value)}
async function req(url,opt,timeout=TIMEOUT){opt=opt||{};const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{return await fetch(url,Object.assign({},opt,{signal:c.signal}))}finally{clearTimeout(t)}}
async function text(url,opt,timeout=TIMEOUT){try{const r=await req(url,opt,timeout);if(!r.ok){log("HTTP "+r.status+" "+url);return null}return await r.text()}catch(e){log("GET failed "+url+": "+e.message);return null}}
async function json(url,opt,timeout=TIMEOUT){try{const r=await req(url,opt,timeout);if(!r.ok){log("HTTP "+r.status+" "+url);return null}return await r.json()}catch(e){log("JSON failed "+url+": "+e.message);return null}}
function attrs(s){const o={};String(s||"").replace(/([^\s=\/>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g,(_,k,a,b,c)=>{o[k.toLowerCase()]=a!==undefined?a:b!==undefined?b:c!==undefined?c:"";return _});return o}
const VOID={area:1,base:1,br:1,col:1,embed:1,hr:1,img:1,input:1,link:1,meta:1,param:1,source:1,track:1,wbr:1};
function unesc(s){return String(s||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function parseHTML(src){const root={tag:"root",a:{},c:[],t:""},st=[root],rx=/<[^>]+>|[^<]+/g;let m;while((m=rx.exec(String(src||"")))){const x=m[0];if(x[0]!=="<"){if(st.length)st[st.length-1].t+=unesc(x);continue}if(/^<!--/.test(x))continue;if(/^<\//.test(x)){const tag=(x.match(/^<\s*\/\s*([^\s>]+)/)||[])[1];if(tag){for(let i=st.length-1;i>0;i--)if(st[i].tag===tag.toLowerCase()){st.length=i;break}}continue}const q=x.match(/^<\s*([^\s/>]+)/);if(!q)continue;const tag=q[1].toLowerCase(),a=attrs(x.slice(q[0].length,-1)),n={tag,a,c:[],t:""};st[st.length-1].c.push(n);if(!VOID[tag]&&!/\/\s*>$/.test(x))st.push(n)}return root}
function hasClass(n,c){return (" "+(n.a.class||"").replace(/\s+/g," ")+" ").indexOf(" "+c+" ")>=0}
function match(n,sel){if(!n||n.tag==="root")return false;let tag=sel.match(/^[a-z0-9_-]+/i);if(tag&&n.tag!==tag[0].toLowerCase())return false;let id=sel.match(/#([a-z0-9_-]+)/i);if(id&&n.a.id!==id[1])return false;let cs=sel.match(/\.([a-z0-9_-]+)/gi)||[];for(const x of cs)if(!hasClass(n,x.slice(1)))return false;return true}
function all(n,sel,out){out=out||[];for(const x of n.c){if(match(x,sel))out.push(x);all(x,sel,out)}return out}
function first(n,sel){return all(n,sel,[])[0]||null}
function val(n,k){return n&&n.a[k.toLowerCase()]||""}
function nodeText(n){let s=n?n.t:"";for(const x of (n&&n.c)||[])s+=nodeText(x);return unesc(s).replace(/\s+/g," ").trim()}
function ints(v){const n=Number(v);return Number.isInteger(n)&&n>0?n:null}
function uniq(a){return [...new Set((a||[]).filter(Boolean).map(String))]}
function norm(v){return String(v||"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"")}
function clean(v){return typeof v==="string"?v.replace(/\\/g,""):v}
async function getMapping(id,s,e,type="tv"){return memo("anikoto:mapping:"+type+":"+id+":"+s+":"+e,MAP_TTL,async()=>{const u=MAPPING_URL+"?tmdbId="+encodeURIComponent(id)+"&mediaType="+encodeURIComponent(type)+"&season="+encodeURIComponent(s)+"&episode="+encodeURIComponent(e),d=await json(u,{headers:{Accept:"application/json","User-Agent":UA}},4500);if(!d||!d.ok||!d.mapping)return null;const m=d.mapping,mal=String(m.mal_id||m.malId||"").trim(),ep=ints(m.mal_episode||m.target_episode);return mal&&ep?{malId:mal,malEpisode:ep,title:String(m.anime_title||m.title||"").trim(),titles:Array.isArray(m.titles)?m.titles.filter(Boolean).map(String):[],source:m.source||"shared"}:null})}
const TMDB_API="https://api.themoviedb.org/3",TMDB_KEY="68e094699525b18a70bab2f86b1fa706";
async function resolveTmdbId(id,type){id=String(id||"").trim();if(/^\d+$/.test(id)||!/^tt\d+$/i.test(id))return id;try{const t=String(type||"tv").toLowerCase()==="movie"?"movie_results":"tv_results",d=await json(TMDB_API+"/find/"+encodeURIComponent(id)+"?api_key="+encodeURIComponent(TMDB_KEY)+"&external_source=imdb_id",{headers:{"Accept":"application/json","User-Agent":UA}},2500),a=d&&Array.isArray(d[t])?d[t]:[];return a[0]&&a[0].id?String(a[0].id):id}catch(e){return id}}
async function tmdbInfo(id,type){try{const t=String(type||"tv").toLowerCase()==="movie"?"movie":"tv",d=await json(TMDB_API+"/"+t+"/"+encodeURIComponent(id)+"?api_key="+encodeURIComponent(TMDB_KEY)+"&language=en-US",{headers:{"Accept":"application/json","User-Agent":UA}},2500);if(!d)return null;return{title:String(d.name||d.title||d.original_name||d.original_title||"").trim(),originalTitle:String(d.original_name||d.original_title||"").trim()}}catch(e){return null}}
async function searchAnime(q){if(!q)return[];return memo("anikoto:search:"+String(q).toLowerCase(),MAP_TTL,async()=>{const d=await json(AJAX_URL+"/anime/search?keyword="+encodeURIComponent(q),{headers:HEADERS});const h=d&&d.result&&d.result.html;if(!h)return[];const root=parseHTML(h),box=first(root,"div.scaff.items"),out=[];if(!box)return out;for(const n of box.c){if(!n.a||!n.a.href)continue;const t=first(n,".name.d-title");if(t)out.push({title:nodeText(t),url:new URL(n.a.href,ANIKOTO_URL).href,image:(first(n,"img")||{a:{}}).a.src||""})}return out})}
function rank(rs,titles){const ts=uniq(titles).map(norm).filter(Boolean);return rs.slice().sort((a,b)=>{const sc=x=>{const t=norm(x.title);if(ts.indexOf(t)>=0)return 100;if(ts.some(y=>t.indexOf(y)>=0||y.indexOf(t)>=0))return 80;return 0};return sc(b)-sc(a)})}
async function episodes(animeUrl){return memo("anikoto:episodes:"+animeUrl,SERVER_TTL,async()=>{const h=await text(animeUrl,{headers:HEADERS});if(!h)return null;const r=parseHTML(h),w=first(r,"#watch-main"),id=w&&val(w,"data-id");if(!id)return null;const d=await json(AJAX_URL+"/episode/list/"+encodeURIComponent(id)+"?vrf=",{headers:HEADERS});const eh=d&&d.result;if(!eh)return null;const er=parseHTML(eh),out=[];for(const a of all(er,"a")){const id=val(a,"data-ids"),num=ints(val(a,"data-num"));if(!num)continue;out.push({episodeId:id,href:val(a,"href"),malId:val(a,"data-mal")||null,episodeNumber:num,title:val(a,"title"),dub:val(a,"data-dub")==="1",filler:hasClass(a,"filler")})}return out})}
async function findEpisode(m){const qs=uniq([m.title,...m.titles]),allr=[];const searchResults=await settled(qs.map(q=>()=>searchAnime(q)),EXTRACT_TIMEOUT);for(const r of searchResults)for(const x of r||[])if(!allr.some(y=>y.url===x.url))allr.push(x);const candidates=rank(allr,qs).slice(0,10),checks=await settled(candidates.map(c=>async()=>{const es=await episodes(c.url);if(!es)return null;const e=es.find(x=>(m.malId?x.malId===m.malId&&x.episodeNumber===m.malEpisode:x.episodeNumber===m.malEpisode)&&x.episodeId);return e?{candidate:c,episode:e,episodes:es}:null}),EXTRACT_TIMEOUT);return checks.find(Boolean)||null}
async function kiwi(mal,ep){const u=MAPPER_URL+"/api/mal/"+encodeURIComponent(mal)+"/"+encodeURIComponent(ep)+"/"+Math.floor(Date.now()/1000),d=await json(u,{headers:HEADERS});return d&&d["Kiwi-Stream-"]||null}
async function serverLinks(id,dub){return memo("anikoto:servers:"+id+":"+(dub?1:0),SERVER_TTL,async()=>{const d=await json(AJAX_URL+"/server/list?servers="+encodeURIComponent(id),{headers:HEADERS});const h=d&&d.result&&d.result.html;if(!h)return[];const r=parseHTML(h),out=[];for(const a of all(r,"a")){const link=val(a,"data-link")||val(a,"href"),name=nodeText(a);if(link)out.push({name,linkId:link,groupName:name})}return out})}
async function serverUrl(id){const d=await json(AJAX_URL+"/server/"+encodeURIComponent(id),{headers:HEADERS});return d&&d.result&&d.result.url||null}
function b64dec(s){try{const bin=atob(String(s||"")),o=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)o[i]=bin.charCodeAt(i);return o}catch(e){return new Uint8Array(0)}}
function b64url(a){let s="";for(const x of a)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function utf8enc(s){return new TextEncoder().encode(String(s))}
function utf8(a){return new TextDecoder().decode(a)}
function sha256(a){return crypto.subtle.digest("SHA-256",a)}
function hmac256(k,m){const kb=utf8enc(k),mb=typeof m==="string"?utf8enc(m):m;return crypto.subtle.importKey("raw",kb,{name:"HMAC",hash:"SHA-256"},false,["sign"]).then(x=>crypto.subtle.sign("HMAC",x,mb))}
function aesCbcDec(data,key,iv){throw new Error("AES implementation unavailable")}
function sourceFile(r){const enc=r&&r.enc;if(typeof enc==="string"&&enc){try{const k=new Uint8Array(32);k.set(utf8enc("i?LMTAx0Q6,:}50U"));const iv=utf8enc("W0;27ToaUpl_P%'c");const p=aesCbcDec(b64dec(enc),k,iv),o=JSON.parse(utf8(p));if(o&&typeof o.file==="string"&&o.file)return o.file}catch(e){log("Megaplay decrypt failed: "+e.message)}}const s=r&&r.sources;if(s&&!Array.isArray(s)&&typeof s.file==="string")return s.file;if(Array.isArray(s)&&s.length&&s[0]&&typeof s[0].file==="string")return s[0].file;return null}
function signMegaplay(u){try{const x=new URL(u),m=x.pathname.match(/\/([a-f0-9]{32})\/([a-f0-9]{32})\//i);if(!m)return u;const p=utf8enc(Math.floor(Date.now()/1000)+90+"|"+m[1].toLowerCase()+"/"+m[2].toLowerCase()),sig=hmac256("MpCdnT0k3n!9f2K#xQ7vL5mR8wN1pY4s",p),q=x.search?x.search+"&":"?";return x.href.split("?")[0]+q+"token="+b64url(p)+"."+b64url(sig)}catch(e){log("Megaplay signing failed: "+e.message);return u}}
function subFormat(u,d){const a=["srt","vtt","ass"],x=String(d||"").toLowerCase().replace(/^\./,"");if(a.indexOf(x)>=0)return x;try{const p=new URL(u).pathname.split(".").pop().toLowerCase();return a.indexOf(p)>=0?p:"vtt"}catch(e){return"vtt"}}
function streamHeaders(ref,origin){return{"Referer":ref,"Origin":origin,"User-Agent":UA,"Accept":"*/*"}}
function cleanStreamUrl(u){return String(u||"").replace(/\\/g,"").trim()}
async function extractVidtube(u,server){const h=await text(u,{headers:HEADERS});if(!h)return[];const r=parseHTML(h),p=first(r,"#megaplay-player"),id=p&&val(p,"data-id");if(!id)return[];const z=new URL(u),parts=z.pathname.split("/").filter(Boolean),type=parts[parts.length-1];if(!type)return[];const d=await json("https://vidtube.site/stream/getSourcesNew?id="+encodeURIComponent(id)+"&type="+encodeURIComponent(type),{headers:{"X-Requested-With":"XMLHttpRequest","Referer":"https://vidtube.site/","Origin":"https://vidtube.site","User-Agent":UA}},10000);const playlist=d&&d.sources&&d.sources.file;if(!playlist)return[];const tr=Array.isArray(d&&d.tracks)?d.tracks:[];let sub=null;for(const x of tr)if(x&&x.kind==="captions"&&String(x.lang||"").toLowerCase()==="english"){sub=x.file;break}if(!sub)for(const x of tr)if(x&&x.kind==="captions"&&x.default===true){sub=x.file;break}sub=cleanStreamUrl(sub);return[{name:server||"vidtube",title:(server||"vidtube")+" [multi-quality]",url:cleanStreamUrl(playlist),quality:"multi-quality",headers:streamHeaders("https://vidtube.site/","https://vidtube.site"),subtitle:sub||"",subtitleFormat:sub?"vtt":"",subtitles:sub?[{url:sub,name:"English",language:"en",format:"vtt",default:true,headers:streamHeaders("https://vidtube.site/","https://vidtube.site")}]:[],backup:false}]}
async function extractMegaplay(u,server){const h=await text(u,{headers:HEADERS});if(!h)return[];const r=parseHTML(h),p=first(r,"#megaplay-player"),id=p&&val(p,"data-id");if(!id)return[];const page=new URL(u);let source=null,file=null;for(const ep of["getSources","getSourcesNew"]){try{let q=page.origin+"/stream/"+ep+"?id="+encodeURIComponent(id),sec=page.searchParams&&page.searchParams.get("s");if(sec)q+="&s="+encodeURIComponent(sec);const d=await json(q,{headers:{"X-Requested-With":"XMLHttpRequest","Referer":u,"Origin":page.origin,"User-Agent":UA,"Accept":"*/*"}},10000),f=sourceFile(d);if(f){source=d;file=cleanStreamUrl(f);break}}catch(e){log("Megaplay "+ep+" failed: "+e.message)}}if(!file||!source)return[];const tr=Array.isArray(source.tracks)?source.tracks:[];let en=null;for(const x of tr)if(x&&x.kind==="captions"&&String(x.label||"").toLowerCase()==="english"){en=x;break}if(!en)for(const x of tr)if(x&&x.kind==="captions"&&x.default===true){en=x;break}const sub=cleanStreamUrl(en&&en.file),fmt=sub?subFormat(sub,en&&en.format):"",signed=signMegaplay(file);log("Megaplay source resolved; signed playback URL generated");return[{name:server||"Megaplay",title:(server||"Megaplay")+" [multi-quality]",url:signed,_megaplayBase:file,quality:"multi-quality",headers:streamHeaders("https://megaplay.buzz/","https://megaplay.buzz/"),subtitle:sub||"",subtitleFormat:fmt,subtitles:sub?[{url:sub,name:"English",language:"en",format:fmt||"vtt",default:true,headers:streamHeaders("https://megaplay.buzz/","https://megaplay.buzz/")}]:[],backup:false}]}
async function extract(u,server){try{const h=new URL(u).hostname.toLowerCase().split(".")[0];if(h==="vidtube")return await extractVidtube(u,server);if(h==="megaplay")return await extractMegaplay(u,server);log("Unsupported extractor host: "+h);return[]}catch(e){log("Extractor "+(server||"unknown")+" failed: "+e.message);return[]}}
async function streamsForEpisode(id,mal,ep,dub){const key="anikoto:streams:"+id+":"+(dub?1:0),hit=CACHE.get(key);if(hit!==undefined){const v=await hit;return v.map(x=>x&&x._megaplayBase?Object.assign({},x,{url:signMegaplay(x._megaplayBase)}):x)}const p=(async()=>{const kp=mal?kiwi(mal,ep).catch(()=>null):Promise.resolve(null),servers=await serverLinks(id,dub),kd=await kp;if(kd&&kd.sub&&kd.sub.url)servers.push({name:"Kiwi",linkId:String(kd.sub.url),groupName:"Kiwi"});if(!servers.length)return[];const urls=await settled(servers.map(s=>async()=>{try{const u=await serverUrl(s.linkId);return u?{s,u}:null}catch(e){log("Server URL "+s.name+" failed: "+e.message);return null}}),EXTRACT_TIMEOUT),extracted=await settled(urls.map(x=>async()=>{if(!x)return[];try{return await extract(x.u,x.s.name)}catch(e){log("Server "+x.s.name+" failed: "+e.message);return[]}}),EXTRACT_TIMEOUT),out=[];for(const got of extracted){for(const item of got||[]){if(item&&item._megaplayBase)item.url=item._megaplayBase;out.push(item)}}return out})();CACHE.set(key,p,STREAM_TTL);try{const out=await p;CACHE.set(key,out,STREAM_TTL);return out.map(x=>x&&x._megaplayBase?Object.assign({},x,{url:signMegaplay(x._megaplayBase)}):x)}catch(e){CACHE.delete(key);throw e}}
async function getStreams(tmdbId,mediaType="tv",season=1,episode=1,settings={}){const type=String(mediaType||"tv").toLowerCase(),rawId=String(tmdbId||"").trim(),id=await resolveTmdbId(rawId,type),s=ints(season)||1,e=ints(episode)||1;if(!id)return[];const deadline=Date.now()+14500,mapped=async()=>{const tryOne=async m=>{if(!m)return null;const hit=await findEpisode(m);if(!hit)return null;const dub=typeof settings==="boolean"?settings:!!(settings&&settings.dub),out=await streamsForEpisode(hit.episode.episodeId,m.malId,m.malEpisode,dub);return out&&out.length?out:null};const mapSeason=type==="movie"?1:s,mapEpisode=type==="movie"?1:e,m=await getMapping(id,mapSeason,mapEpisode,type),out=await tryOne(m);return out||null};try{const out=await timeout(mapped(),Math.min(9000,Math.max(500,deadline-Date.now())));if(out&&out.length)return out}catch(e){log("Mapped path failed: "+e.message)}const fallback=async()=>{const info=await tmdbInfo(id,type);if(!info||!info.title)return[];const title=info.title,titles=info.originalTitle&&norm(info.originalTitle)!==norm(title)?[info.originalTitle]:[],fm={malId:"",malEpisode:type==="movie"?1:e,title,titles:uniq(titles)},hit=await findEpisode(fm);if(!hit){log("Original AniKoto fallback episode not found for "+title);return[]}const dub=typeof settings==="boolean"?settings:!!(settings&&settings.dub),out=await streamsForEpisode(hit.episode.episodeId,"",hit.episode.episodeNumber,dub);log("Original AniKoto fallback streams: "+out.length);return out||[]};try{return await timeout(fallback(),Math.max(100,deadline-Date.now()))}catch(e){log("AniKoto deadline reached: "+e.message);return[]}}
module.exports={getStreams};
