const API="https://api.animeonsen.xyz/v4",AUTH="https://auth.animeonsen.xyz/oauth/token",CDN="https://cdn.animeonsen.xyz",SITE="https://www.animeonsen.xyz",MAPPING_URL="https://breezy-plugins.netlify.app/.netlify/functions/anime-mapping",UA="Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/AD1A.240418.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.54 Mobile Safari/537.36";
const CLIENT_ID="f296be26-28b5-4358-b5a1-6259575e23b7",CLIENT_SECRET="349038c4157d0480784753841217270c3c5b35f4281eaee029de21cb04084235";
let token=null,tokenExpiration=0,tokenPromise=null;
function log(x){console.log("[AnimeOnsen] "+x)}
async function req(url,opt){opt=opt||{};const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{return await fetch(url,Object.assign({},opt,{signal:c.signal}))}finally{clearTimeout(t)}}
async function json(url,opt){try{const r=await req(url,opt);if(!r.ok){log("HTTP "+r.status+" "+url);return null}return await r.json()}catch(e){log("Request failed "+url+": "+e.message);return null}}
async function getToken(){const now=Math.floor(Date.now()/1000);if(token&&tokenExpiration>now+3600)return token;if(tokenPromise)return tokenPromise;tokenPromise=(async()=>{const body={client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:"client_credentials"},r=await req(AUTH,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json","User-Agent":UA},body:JSON.stringify(body)});if(!r.ok)throw new Error("AnimeOnsen token HTTP "+r.status);const d=await r.json();if(!d.access_token)throw new Error("AnimeOnsen token missing");token=d.access_token;tokenExpiration=now+Number(d.expires_in||3600);log("OAuth token refreshed");return token})().finally(()=>{tokenPromise=null});return tokenPromise}
async function api(path,retry=true){const t=await getToken(),d=await json(API+path,{headers:{"Authorization":"Bearer "+t,"Accept":"application/json","User-Agent":UA}});if(!d&&retry){token=null;tokenExpiration=0;try{await getToken();return api(path,false)}catch(e){}}return d}
async function mapping(tmdbId,season,episode){const u=MAPPING_URL+"?tmdbId="+encodeURIComponent(tmdbId)+"&season="+encodeURIComponent(season)+"&episode="+encodeURIComponent(episode),d=await json(u,{headers:{"Accept":"application/json","User-Agent":UA}});if(!d||!d.ok||!d.mapping)return null;const m=d.mapping,mal=String(m.mal_id||m.malId||"").trim(),ep=Number(m.mal_episode||m.target_episode||0);if(!mal||!ep)return null;return{malId:mal,malEpisode:ep,title:String(m.anime_title||"").trim(),titles:Array.isArray(m.titles)?m.titles.filter(Boolean).map(String):[]}}
async function search(query){query=String(query||"").replace(/-/g,"");if(!query)return[];const d=await api("/search/"+encodeURIComponent(query));if(!d||!Array.isArray(d.result))return[];return d.result.map(x=>({name:x.content_title_en||x.content_title||"",alias:String(x.content_id||""),imageUrl:x.content_id?API+"/image/210x300/"+encodeURIComponent(x.content_id):""})).filter(x=>x.alias)}
function normalize(s){return String(s||"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"").trim()}
async function findAnime(m){const queries=[m.title,...m.titles].filter(Boolean),all=[];for(const q of queries){const rs=await search(q);for(const x of rs)if(!all.some(y=>y.alias===x.alias))all.push(x);const exact=rs.find(x=>x.name===q);if(exact)return exact}for(const q of queries){const n=normalize(q),exact=all.find(x=>normalize(x.name)===n);if(exact)return exact}return all[0]||null}
async function getEpisodes(alias){const d=await api("/content/"+encodeURIComponent(alias)+"/episodes");if(!d||typeof d!=="object")return[];const out=[];for(const k of Object.keys(d)){const n=Number(k);if(!Number.isInteger(n)||n<1)continue;const x=d[k]||{};out.push({episodeNumber:n,episodeTitle:x.contentTitle_episode_en||null,episodeLink:n+"+"+alias})}return out.sort((a,b)=>a.episodeNumber-b.episodeNumber)}
async function getStreams(tmdbId,mediaType="tv",season=1,episode=1,settings={}){try{if(String(mediaType).toLowerCase()!=="tv")return[];const m=await mapping(tmdbId,season,episode);if(!m){log("No mapping for TMDB="+tmdbId+" S"+season+"E"+episode);return[]}const anime=await findAnime(m);if(!anime){log("AnimeOnsen search failed for "+m.title);return[]}log("Matched "+anime.name+" -> "+anime.alias);const eps=await getEpisodes(anime.alias),ep=eps.find(x=>x.episodeNumber===m.malEpisode);if(!ep){log("Episode "+m.malEpisode+" not found for "+anime.name);return[]}const t=await getToken(),n=ep.episodeNumber,url=CDN+"/video/mp4-dash/"+encodeURIComponent(anime.alias)+"/"+encodeURIComponent(n)+"/manifest.mpd",subtitle=API+"/subtitles/"+encodeURIComponent(anime.alias)+"/en-US/"+encodeURIComponent(n),headers={"Referer":SITE+"/","User-Agent":UA};return[{name:"AnimeOnsen",title:"AnimeOnsen [DASH]",url,quality:"single",headers,subtitle,subtitleFormat:"ASS",backup:false}]}catch(e){log("Fatal: "+e.message);return[]}}
module.exports={getStreams};
