const BASE="https://anizone.to",MAPPING_URL="https://anikoto-nuvio.netlify.app/.netlify/functions/anime-mapping",UA="Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/AD1A.240418.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.54 Mobile Safari/537.36",MAP_TTL=86400000,SEARCH_TTL=86400000,EPISODE_TTL=3600000,STREAM_TTL=1800000,REQ_TIMEOUT=10000,FAST_TIMEOUT=4500;
function log(x){console.log("[AniZone] "+x)}
class NuvioCache{constructor(){this.m=new Map()}get(k){const x=this.m.get(k);if(!x)return; if(x.e<=Date.now()){this.m.delete(k);return}return x.v}set(k,v,t){this.m.set(k,{v,e:Date.now()+t});return v}delete(k){this.m.delete(k)}clear(){this.m.clear()}}
const CACHE=globalThis.__NUVIO_ANIZONE_CACHE__||(globalThis.__NUVIO_ANIZONE_CACHE__=new NuvioCache);
function cacheGet(k){return CACHE.get(k)}
function cacheSet(k,v,t){return CACHE.set(k,v,t)}
async function memo(k,t,fn){const hit=cacheGet(k);if(hit!==undefined)return hit;const p=Promise.resolve().then(fn);cacheSet(k,p,t);try{const v=await p;cacheSet(k,v,t);return v}catch(e){CACHE.delete(k);throw e}}
async function timeout(p,ms=FAST_TIMEOUT){let timer;try{return await Promise.race([p,new Promise((_,reject)=>timer=setTimeout(()=>reject(new Error("timeout")),ms))])}finally{clearTimeout(timer)}}
async function allSettledMap(items,fn,ms=FAST_TIMEOUT){const r=await Promise.allSettled(items.map(x=>timeout(Promise.resolve().then(()=>fn(x)),ms)));return r.map(x=>x.status==="fulfilled"?x.value:null).filter(Boolean)}
async function req(url,opt={},ms=REQ_TIMEOUT){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(t)}}
async function text(url,opt={},ms=REQ_TIMEOUT){try{const r=await req(url,opt,ms);if(!r.ok){log("HTTP "+r.status+" "+url);return null}return await r.text()}catch(e){log("Request failed "+url+": "+e.message);return null}}
async function json(url,opt={},ms=REQ_TIMEOUT){try{const r=await req(url,opt,ms);if(!r.ok){log("HTTP "+r.status+" "+url);return null}return await r.json()}catch(e){log("JSON request failed "+url+": "+e.message);return null}}
function attrs(s){const o={};let i=0,n=String(s||"");while(i<n.length){while(i<n.length&&/[\s\/]/.test(n[i]))i++;let k="";while(i<n.length&&/[^\s=\/>]/.test(n[i]))k+=n[i++];if(!k)break;while(i<n.length&&/\s/.test(n[i]))i++;let v="";if(n[i]==="="){i++;while(i<n.length&&/\s/.test(n[i]))i++;if(n[i]==='"'||n[i]==="'"){const q=n[i++];while(i<n.length&&n[i]!==q)v+=n[i++];if(n[i]===q)i++}else while(i<n.length&&!/[\s>]/.test(n[i]))v+=n[i++]}o[k.toLowerCase()]=v}return o}
const VOID={area:1,base:1,br:1,col:1,embed:1,hr:1,img:1,input:1,link:1,meta:1,param:1,source:1,track:1,wbr:1};
function unesc(s){return String(s||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function parseHTML(src){const root={tag:"root",a:{},c:[],t:""},stack=[root],s=String(src||"");let i=0;while(i<s.length){if(s[i]!=="<"){let j=s.indexOf("<",i);if(j<0)j=s.length;stack[stack.length-1].t+=unesc(s.slice(i,j));i=j;continue}if(s.slice(i,i+4)==="<!--"){const j=s.indexOf("-->",i+4);i=j<0?s.length:j+3;continue}if(/^<!doctype/i.test(s.slice(i,i+10))){const j=s.indexOf(">",i+2);i=j<0?s.length:j+1;continue}if(s.slice(i,i+2)==="</"){const m=/^<\s*\/\s*([^\s>]+)/.exec(s.slice(i));if(m){const j=s.indexOf(">",i+m[0].length);i=j<0?s.length:j+1;const tag=m[1].toLowerCase();for(let k=stack.length-1;k>0;k--)if(stack[k].tag===tag){stack.length=k;break}continue}}const m=/^<\s*([^\s/>]+)/.exec(s.slice(i));if(!m){i++;continue}let j=i+m[0].length,q=null;for(let k=j;k<s.length;k++){const ch=s[k];if(ch==="'"||ch==='"'){if(q===null)q=ch;else if(q===ch)q=null}else if(ch===">"&&q===null){j=k;break}}if(j<=i){i++;continue}const raw=s.slice(i,j+1),tag=m[1].toLowerCase(),a=attrs(raw.slice(m[0].length,-1)),node={tag,a,c:[],t:""};stack[stack.length-1].c.push(node);i=j+1;if(!VOID[tag]&&!/\/\s*>$/.test(raw)){stack.push(node);if(tag==="script"||tag==="style"){const close=new RegExp("<\\/\\s*"+tag+"\\s*>","i"),tail=s.slice(i),cm=close.exec(tail);if(cm){node.t+=tail.slice(0,cm.index);i+=cm.index+cm[0].length;stack.pop()}}}}return root}
function children(n){return n&&Array.isArray(n.c)?n.c:[]}
function hasClass(n,c){return(" "+String(n&&n.a&&n.a.class||"").replace(/\s+/g," ")+" ").includes(" "+c+" ")}
function match(n,sel){if(!n||n.tag==="root")return false;const tm=sel.match(/^[a-z0-9_-]+/i);if(tm&&n.tag!==tm[0].toLowerCase())return false;const im=sel.match(/#([a-z0-9_-]+)/i);if(im&&n.a.id!==im[1])return false;const cm=sel.match(/\.([a-z0-9_-]+)/gi)||[];for(const c of cm)if(!hasClass(n,c.slice(1)))return false;return true}
function all(n,sel,out=[]){for(const x of children(n)){if(match(x,sel))out.push(x);all(x,sel,out)}return out}
function first(n,sel){return all(n,sel,[])[0]||null}
function nodeText(n){let s=n&&n.t||"";for(const x of children(n))s+=nodeText(x);return unesc(s).replace(/\s+/g," ").trim()}
function decodeJSON(s){try{return JSON.parse(String(s||"").replace(/\\u0022/g,'"').replace(/\\u0027/g,"'"))}catch(e){log("JSON decode failed: "+e.message);return null}}
function extractJSONParse(s){const x=String(s||"");let m=/JSON\.parse\(\s*(['"])([\s\S]*?)\1\s*\)/.exec(x);if(!m)return null;let raw=m[2];try{raw=raw.replace(/\\'/g,"'").replace(/\\"/g,'"')}catch(e){}return decodeJSON(raw)}
function clean(v){return typeof v==="string"?v.replace(/\\/g,"").trim():v}
function uniq(a){return[...new Set((a||[]).filter(Boolean).map(String))]}
function norm(s){return String(s||"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"")}
function exact(results,q){const n=norm(q);return results.find(x=>norm(x.name)===n)||results.find(x=>String(x.name||"").toLowerCase()===String(q).toLowerCase())||null}

async function mapping(tmdbId,season,episode){const key="mapping:"+tmdbId+":"+season+":"+episode;return memo(key,MAP_TTL,async()=>{const url=MAPPING_URL+"?tmdbId="+encodeURIComponent(tmdbId)+"&season="+encodeURIComponent(season)+"&episode="+encodeURIComponent(episode);const d=await json(url,{headers:{Accept:"application/json","User-Agent":UA}},7000);if(!d||!d.ok||!d.mapping)return null;const m=d.mapping,mal=String(m.mal_id||m.malId||"").trim(),ep=Number(m.mal_episode||m.target_episode||0);if(!mal||!ep)return null;return{malId:mal,malEpisode:ep,title:String(m.anime_title||"").trim(),titles:Array.isArray(m.titles)?m.titles.filter(Boolean).map(String):[]}})}

async function search(query){query=String(query||"").trim();if(!query)return[];return memo("search:"+query.toLowerCase(),SEARCH_TTL,async()=>{const url=BASE+"/anime?search="+encodeURIComponent(query);const html=await text(url,{headers:{Accept:"text/html,application/xhtml+xml","Accept-Encoding":"gzip, br","User-Agent":UA}},FAST_TIMEOUT);if(!html)return[];const main=/<main\b[^>]*>([\s\S]*?)<\/main>/i.exec(html);const src=main?main[1]:html;let m=/x-data\s*=\s*(["'])([\s\S]*?)\1/i.exec(src),parsed=m?extractJSONParse(m[2]):null;if(!Array.isArray(parsed)){const jm=/JSON\.parse\(\s*(['"])([\s\S]*?)\1\s*\)/s.exec(src);if(jm)parsed=extractJSONParse(jm[0])}if(!Array.isArray(parsed))return[];const out=[];for(const item of parsed){if(!item)continue;const title=item.main_title,img=item.cover,href=item.url;if(title==null||href==null)continue;out.push({name:String(title),alias:clean(href),imageUrl:clean(img||"")})}return out})}

async function findAnime(m){const qs=uniq([m.title,...m.titles]);if(!qs.length)return null;const key="find:"+qs.map(norm).sort().join("|");return memo(key,SEARCH_TTL,async()=>{const results=await allSettledMap(qs,search,FAST_TIMEOUT);for(let i=0;i<qs.length;i++){const r=results[i]||[];const x=exact(r,qs[i]);if(x)return x}let fallback=null;for(const r of results)if(r&&r.length){fallback=r[0];break}return fallback})}

async function getEpisodes(alias){return memo("episodes:"+alias,EPISODE_TTL,async()=>{const html=await text(alias,{headers:{Accept:"text/html,application/xhtml+xml","Accept-Encoding":"gzip, br","User-Agent":UA}},FAST_TIMEOUT);if(!html)return[];const main=/<main\b[^>]*>([\s\S]*?)<\/main>/i.exec(html);const src=main?main[1]:html;const x=/x-data\s*=\s*(["'])([\s\S]*?)\1/i.exec(src);if(!x)return[];const data=x[2];let im=/items\s*:\s*JSON\.parse\(\s*(['"])([\s\S]*?)\1\s*\)/s.exec(data),list=im?extractJSONParse(im[0]):null;if(!Array.isArray(list)){const jm=/JSON\.parse\(\s*(['"])([\s\S]*?)\1\s*\)/s.exec(data);if(jm)list=extractJSONParse(jm[0])}if(!Array.isArray(list))return[];const out=[];let n=0;for(const item of list){if(!item||!item.url)continue;n++;out.push({episodeLink:clean(item.url),episodeNumber:n,thumbnail:clean(item.snapshot||""),episodeTitle:item.title_list&&item.title_list["1"]||"",isFiller:String(item.type||"").toLowerCase()==="filler",hasDub:false})}log("Episodes parsed: "+out.length);return out})}

async function getEpisodeStream(episodeUrl){return memo("stream:"+episodeUrl,STREAM_TTL,async()=>{const html=await text(episodeUrl,{headers:{Accept:"text/html,application/xhtml+xml","Accept-Encoding":"gzip, br","User-Agent":UA}},FAST_TIMEOUT);if(!html)return null;const block=/<div\b[^>]*class\s*=\s*(["'])[^"']*\bmb-8\b[^"']*\1[^>]*>([\s\S]*?)<\/div>/i.exec(html);const src=block?block[2]:html;const x=/x-data\s*=\s*(["'])([\s\S]*?)\1/i.exec(src);if(!x)return null;const parsed=extractJSONParse(x[2]);if(!parsed||!parsed.src)return null;const streamSrc=clean(parsed.src);if(!streamSrc)return null;const subs=Array.isArray(parsed.subtitles)?parsed.subtitles:[];const en=subs.find(x=>x&&String(x.language||"").toLowerCase()==="en"&&x.default===true)||subs.find(x=>x&&String(x.language||"").toLowerCase()==="en");const btn=/<button\b[^>]*class\s*=\s*(["'])[^"']*\bflex\b[^"']*\bgap-2\b[^"']*\brelative\b[^"']*\1[^>]*>([\s\S]*?)<\/button>/i.exec(html);const sourceName=btn?unesc(btn[2].replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim():"Default";const subtitles=en&&en.file?clean(en.file):"";return{name:"AniZone",title:"AniZone • "+sourceName,url:streamSrc,quality:"multi-quality",headers:{Referer:BASE+"/","User-Agent":UA},subtitle:subtitles,subtitleFormat:en&&en.format?String(en.format):"",subtitles:subtitles?[{url:subtitles,name:"English",language:"en",format:en&&en.format?String(en.format):"",default:true,headers:{Referer:BASE+"/","User-Agent":UA}}]:[],backup:false,isM3U8:/\.m3u8(?:$|\?)/i.test(streamSrc)})})}

async function getStreams(tmdbId,mediaType="tv",season=1,episode=1,settings={}){try{if(String(mediaType).toLowerCase()!=="tv")return[];const id=String(tmdbId||"").trim(),s=Number(season)||1,e=Number(episode)||1;if(!id)return[];const finalKey="final:"+id+":"+s+":"+e,fast=cacheGet(finalKey);if(fast!==undefined){const result=await fast;log("L1 stream cache hit");return result}const p=(async()=>{const m=await mapping(id,s,e);if(!m){log("No mapping for TMDB="+id+" S"+s+"E"+e);return[]}log("Mapping hit: MAL="+m.malId+" E"+m.malEpisode);const anime=await findAnime(m);if(!anime){log("Anime not found: "+m.title);return[]}log("AniZone match: "+anime.name);const eps=await getEpisodes(anime.alias);if(!eps.length){log("No AniZone episodes");return[]}const ep=eps.find(x=>x.episodeNumber===m.malEpisode);if(!ep){log("Episode "+m.malEpisode+" not found; available="+eps.length);return[]}const stream=await getEpisodeStream(ep.episodeLink);return stream?[stream]:[]})();cacheSet(finalKey,p,STREAM_TTL);try{const result=await p;cacheSet(finalKey,result,STREAM_TTL);return result}catch(e){CACHE.delete(finalKey);throw e}}catch(e){log("Fatal: "+e.message);return[]}}
module.exports={getStreams};
