const BASE="https://anizone.to",MAPPING_URL="https://anikoto-nuvio.netlify.app/.netlify/functions/shared-mapping",UA="Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/AD1A.240418.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.54 Mobile Safari/537.36";
function log(x){console.log("[AniZone] "+x)}
async function req(url,opt){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);const r=await fetch(url,{...(opt||{}),signal:c.signal});clearTimeout(t);return r}catch(e){return null}}
async function text(url,opt){try{const r=await req(url,opt);if(!r.ok){log("HTTP "+r.status+" "+url);return null}return await r.text()}catch(e){log("Request failed "+url+": "+e.message);return null}}
async function json(url,opt){try{const r=await req(url,opt);if(!r.ok){log("HTTP "+r.status+" "+url);return null}return await r.json()}catch(e){log("JSON request failed "+url+": "+e.message);return null}}
function attrs(s){const o={};String(s||"").replace(/([:\w-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g,(m,k,a,b,c)=>{o[k]=a!=null?a:b!=null?b:c!=null?c:"";return m});return o}
function parseHTML(html){const root={type:"root",children:[]},stack=[root],src=String(html||""),re=/<\/?([a-zA-Z0-9:-]+)([^>]*)>/g;let last=0,m;while((m=re.exec(src))){if(m.index>last)stack[stack.length-1].children.push({type:"text",text:src.slice(last,m.index)});const full=m[0],name=m[1].toLowerCase();if(full[1]==="/"){for(let i=stack.length-1;i>0;i--)if(stack[i].name===name){stack.length=i;break}}else if(full[1]!=="!"){const n={type:"element",name,attrs:attrs(m[2]),children:[]};stack[stack.length-1].children.push(n);if(!/\/>$/.test(full)&&!["area","base","br","col","embed","hr","img","input","link","meta","param","source","track","wbr"].includes(name))stack.push(n)}last=re.lastIndex}if(last<src.length)stack[stack.length-1].children.push({type:"text",text:src.slice(last)});return root}
function children(n){return n&&n.children||[]}
function match(n,sel){if(!n||n.type!=="element")return false;return n.name===sel.toLowerCase()}
function all(root,sel){const out=[];function walk(n){if(n&&n.type==="element"&&match(n,sel))out.push(n);for(const c of children(n))walk(c)}walk(root);return out}
function first(root,sel){return all(root,sel)[0]||null}
function nodeText(n){if(!n)return"";if(n.type==="text")return n.text||"";return children(n).map(nodeText).join("")}
function attr(n,k){return n&&n.attrs?n.attrs[k]:undefined}
function decodeJSON(s){try{return JSON.parse(String(s||"").replace(/\\u0022/g,'"').replace(/\\u0026/g,"&").replace(/\\'/g,"'").replace(/\\\//g,"/").replace(/\\\\/g,"\\"))}catch(e){return null}}
async function mapping(tmdbId,season,episode){const u=MAPPING_URL+"?tmdbId="+encodeURIComponent(tmdbId)+"&mediaType=tv&season="+encodeURIComponent(season)+"&episode="+encodeURIComponent(episode),d=await json(u,{headers:{"Accept":"application/json","User-Agent":UA}});if(!d||!d.ok||!d.mapping)return null;const m=d.mapping,mal=String(m.mal_id||m.malId||"").trim(),ep=Number(m.mal_episode||m.target_episode||0);if(!mal||!ep)return null;return{malId:mal,malEpisode:ep,title:String(m.anime_title||m.title||"").trim(),titles:Array.isArray(m.titles)?m.titles.filter(Boolean).map(String):[]}}
async function search(query){query=String(query||"").trim();if(!query)return[];const url=BASE+"/anime?search="+encodeURIComponent(query),html=await text(url,{headers:{"Accept":"text/html,application/xhtml+xml","User-Agent":UA}});if(!html)return[];const root=parseHTML(html),main=first(root,"main");if(!main)return[];const kids=children(main);if(kids.length<2)return[];const data=attr(kids[1],"x-data")||"",m=data.match(/items:\s*JSON\.parse$begin:math:text$\'\(\.\+\?\)\'$end:math:text$/s);if(!m)return[];const list=decodeJSON(m[1]);if(!Array.isArray(list))return[];const out=[];for(const item of list){const title=item&&item.main_title,img=item&&item.cover,href=item&&item.url;if(title==null||img==null||href==null)continue;out.push({name:String(title),alias:String(href).replace(/\\/g,""),imageUrl:String(img)})}return out}
function exactResult(results,query){return results.find(x=>String(x&&x.name||"")===String(query))||null}
async function findAnime(m){const qs=[];if(m.title)qs.push(m.title);for(const t of m.titles||[])if(t&&!qs.includes(t))qs.push(t);if(!qs.length)return null;let fallback=null;for(let i=0;i<qs.length;i++){const q=String(qs[i]).trim();if(!q)continue;const r=await search(q);if(!r.length)continue;const exact=exactResult(r,q);if(exact){log("Exact AniZone match: "+exact.name);return exact}if(!fallback){fallback=r[0];log("No exact match; fallback: "+fallback.name)}}return fallback}
async function getEpisodes(alias){const html=await text(alias,{headers:{"Accept":"text/html,application/xhtml+xml","User-Agent":UA}});if(!html)return[];const root=parseHTML(html),main=first(root,"main");if(!main)return[];const kids=children(main);if(!kids.length)return[];const data=attr(kids[0],"x-data")||"",m=data.match(/items:\s*JSON\.parse$begin:math:text$\'\(\.\+\?\)\'$end:math:text$/s);if(!m)return[];const list=decodeJSON(m[1]);if(!Array.isArray(list))return[];const out=[];let i=1;for(const item of list){if(!item||!item.url)continue;out.push({episodeLink:String(item.url).replace(/\\/g,""),episodeNumber:i,thumbnail:item.snapshot?String(item.snapshot).replace(/\\/g,""):"",episodeTitle:item.title_list&&item.title_list["1"],isFiller:String(item.type||"").toLowerCase()==="filler",hasDub:false});i++}return out}
async function getEpisodeStream(episodeUrl){const html=await text(episodeUrl,{headers:{"Accept":"text/html,application/xhtml+xml","User-Agent":UA}});if(!html)return null;const root=parseHTML(html),div=first(root,"div.mb-8");if(!div)return null;const kids=children(div);if(!kids.length)return null;const data=attr(kids[0],"x-data")||"",parsed=decodeJSON((data.match(/JSON\.parse$begin:math:text$\'\(\.\+\?\)\'$end:math:text$/s)||[])[1]);if(!parsed||!parsed.src)return null;const src=String(parsed.src).replace(/\\/g,""),subs=Array.isArray(parsed.subtitles)?parsed.subtitles:[],en=subs.find(x=>x&&x.language==="en"&&x.default===true),subtitleList=subs.map(x=>({url:x&&x.file?String(x.file).replace(/\\/g,""):"",name:x&&x.title||x&&x.language||"English",language:x&&x.language||"en"})).filter(x=>x.url),button=first(root,"button.flex.gap-2.relative");return{name:"AniZone",title:"AniZone • "+(button?nodeText(button):"Default"),url:src,quality:"multi-quality",preferredQuality:"1080p",headers:{"Referer":BASE+"/","User-Agent":UA},subtitle:en&&en.file?String(en.file).replace(/\\/g,""):"",subtitleFormat:en&&en.format?String(en.format):"",subtitles:subtitleList,backup:false}}
async function getStreams(tmdbId,mediaType="tv",season=1,episode=1,settings={}){try{if(String(mediaType).toLowerCase()!=="tv")return[];const m=await mapping(tmdbId,season,episode);if(!m){log("No mapping");return[]}log("Mapping -> MAL "+m.malId+" E"+m.malEpisode+" "+m.title);const anime=await findAnime(m);if(!anime){log("Anime not found");return[]}log("Selected -> "+anime.name+" "+anime.alias);const eps=await getEpisodes(anime.alias);if(!eps.length){log("No episodes");return[]}const ep=eps.find(x=>x.episodeNumber===m.malEpisode);if(!ep){log("MAL episode "+m.malEpisode+" not found in AniZone episode list ("+eps.length+" episodes)");return[]}log("Mapped episode -> "+ep.episodeNumber+" "+ep.episodeLink);const stream=await getEpisodeStream(ep.episodeLink);if(stream)return[stream];return[]}catch(e){log("Fatal: "+e.message);return[]}}
module.exports={getStreams};
