"use strict";
// Kaa.lt provider port: direct API catalog, episode listing and embedded HLS extraction.

const MAPPING_URL="https://anikoto-nuvio.netlify.app/.netlify/functions/anime-lazy-mapping";
const UA="Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/AD1A.240418.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.54 Mobile Safari/537.36";
async function _req(url,opt={},ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opt,headers:{"User-Agent":UA,"Accept":"*/*",...(opt.headers||{})},signal:c.signal})}finally{clearTimeout(t)}}
async function _json(url,opt={},ms=9000){try{const r=await _req(url,opt,ms);if(!r.ok)return null;return await r.json()}catch(e){return null}}
async function _text(url,opt={},ms=9000){try{const r=await _req(url,opt,ms);if(!r.ok)return "";return await r.text()}catch(e){return ""}}
async function _mapping(tmdbId,season,episode){const u=MAPPING_URL+"?tmdb_id="+encodeURIComponent(tmdbId)+"&tmdbId="+encodeURIComponent(tmdbId)+"&season="+encodeURIComponent(season)+"&episode="+encodeURIComponent(episode)+"&pending=1";const d=await _json(u,{},5500);if(!d||!d.ok||!d.mapping)return null;const m=d.mapping,malId=String(m.mal_id||m.malId||"").trim(),malEpisode=Number(m.mal_episode||m.target_episode||0);if(!malId||!Number.isInteger(malEpisode)||malEpisode<1)return null;return {malId,episode:malEpisode,title:String(m.anime_title||m.title||"").trim(),titles:Array.isArray(m.titles)?m.titles.filter(Boolean).map(String):[]}}
async function _anilistId(malId){const q='query($idMal:Int){Media(idMal:$idMal,type:ANIME){id title{english romaji native}}}';const d=await _json("https://graphql.anilist.co",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({query:q,variables:{idMal:Number(malId)}})},7000);const m=d&&d.data&&d.data.Media;return m&&m.id?{id:String(m.id),titles:[m.title.english,m.title.romaji,m.title.native].filter(Boolean)}:null}
function _lang(settings){const x=String(settings&& (settings.language||settings.audio||settings.lang)||"sub").toLowerCase();return x.includes("dub")?"dub":"sub"}
function _unique(a){return [...new Set((a||[]).filter(Boolean))]}
function _decodeAnimeX(u){if(!String(u).includes('/uwu/'))return {url:u,referer:""};try{let tok=String(u).split('/uwu/').pop();tok=tok.replace(/-/g,'+').replace(/_/g,'/');while(tok.length%4)tok+='=';const raw=atob(tok),key='10b06cdc1ca48c9fb0b94af97cc040cf';let s='';for(let i=0;i<raw.length;i++)s+=String.fromCharCode(raw.charCodeAt(i)^key.charCodeAt(i%key.length));const p=s.split('\0');return {url:p[0]||u,referer:p[1]||''}}catch(e){return {url:u,referer:''}}}

const BASE="https://kaa.lt",KRUSS="https://krussdomi.com/";
function fixUrl(u){return String(u||"").replace(/^https:\/\/\//,"https://").replace(/^http:\/\/\//,"http://").replace(/^\/\//,"https://")}
function extractUrls(s,re){return _unique((String(s||"").match(re)||[]).map(fixUrl))}
async function resolveKaa(m,lang){const searchTitles=_unique([m.title,...m.titles]);const al=await _anilistId(m.malId);if(al)searchTitles.push(...al.titles);let slug="";for(const title of _unique(searchTitles)){const d=await _json(BASE+"/api/search",{method:"POST",headers:{"Content-Type":"application/json","Referer":BASE+"/"},body:JSON.stringify({query:title})},6500);const hits=Array.isArray(d)?d:(d&&d.result)||[];const norm=x=>String(x||"").toLowerCase().replace(/[^a-z0-9]+/g,"");const h=hits.find(x=>norm(x.title)===norm(title))||hits[0];if(h&&h.slug){slug=h.slug;break}}if(!slug)return[];const locale=lang==="dub"?"en-US":"ja-JP";const eps=await _json(`${BASE}/api/show/${encodeURIComponent(slug)}/episodes?ep=${m.episode}&lang=${locale}`,{headers:{"Referer":BASE+"/"}},7000);const list=(eps&&eps.result)||[];const ep=list.find(x=>Number(x.episode_number)===m.episode);if(!ep||!ep.slug)return[];const watch=`${BASE}/${slug}/ep-${m.episode}-${ep.slug}`;const html=await _text(watch,{headers:{"Referer":BASE+"/"}},8500);const clean=html.replace(/\u002F/g,"/").replace(/\\//g,"/");const players=[];const pr=/\{\s*name:\s*["']([^"']+)["']\s*,\s*shortName:\s*["']([^"']+)["']\s*,\s*src:\s*["']([^"']+)["']\s*\}/g;let x;while((x=pr.exec(clean)))if(x[3]&&!/type=dash/i.test(x[3]))players.push(x[3]);if(!players.length)players.push(...extractUrls(clean,/(?:https?:)?\/\/[^\s"'<>]+\/cat-player\/player\?[^\s"'<>]+/g));const results=[];for(const [i,src] of players.slice(0,4).entries()){const embed=await _text(src,{headers:{"Referer":watch}},7500);const master=extractUrls(embed,/(?:https?:)?\/\/[^\s"'<>]+\.m3u8[^\s"'<>]*/g)[0];if(!master)continue;const subtitles=extractUrls(embed,/(?:https?:)?\/\/[^\s"'<>]+\.(?:vtt|srt)[^\s"'<>]*/gi).filter(u=>!u.toLowerCase().includes("preview")).map(url=>({url,language:"en",format:/\.vtt/i.test(url)?"vtt":"srt"}));results.push({name:"Kaa",title:["Nico","Robin","D'Luff","Kaa "+(i+1)][Math.min(i,3)],url:master,quality:"auto",type:"m3u8",headers:{Referer:KRUSS,Origin:"https://krussdomi.com","User-Agent":UA},subtitles,backup:false})}return results}
async function getStreams(tmdbId,mediaType="tv",season=1,episode=1,settings={}){try{if(String(mediaType).toLowerCase()!=="tv")return[];const m=await _mapping(tmdbId,season,episode);if(!m)return[];return await resolveKaa(m,_lang(settings))}catch(e){console.log("[Kaa] "+String(e&&e.message||e));return[]}}
module.exports={getStreams};
