const LAZY_URL="https://anikoto-nuvio.netlify.app/.netlify/functions/anime-lazy-mapping",NORMAL_URL="https://anikoto-nuvio.netlify.app/.netlify/functions/anime-mapping",POPULATE_URL="https://anikoto-nuvio.netlify.app/.netlify/functions/anime-lazy-populate-background",UA="Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/AD1A.240418.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.54 Mobile Safari/537.36",TTL=86400000,MOVIE_TTL=300000;
const STATE=globalThis.__ANIKOTO_SHARED_MAPPING__||(globalThis.__ANIKOTO_SHARED_MAPPING__={values:new Map(),inflight:new Map()});
function log(x){console.log("[SHARED MAPPING] "+x)}
function key(id,type,s,e){return String(type||"tv").toLowerCase()+":"+String(id)+":"+String(s)+":"+String(e)}
function valid(m){if(!m)return null;const mal=String(m.mal_id||m.malId||"").trim();if(!mal)return null;const ep=Number(m.mal_episode||m.target_episode||m.malEpisode||0);if(!Number.isInteger(ep)||ep<1)return null;return{...m,mal_id:mal,mal_episode:ep}}
async function req(url,timeout=5000,opt={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{return await fetch(url,{...opt,headers:{Accept:"application/json","User-Agent":UA,...(opt.headers||{})},signal:c.signal})}catch(e){return null}finally{clearTimeout(t)}}
async function json(url,timeout=5000,opt={}){try{const r=await req(url,timeout,opt);if(!r||!r.ok)return null;return await r.json()}catch(e){return null}}
function save(k,v,ttl){STATE.values.set(k,{v,expires:Date.now()+ttl});return v}
function get(k){const x=STATE.values.get(k);if(!x)return undefined;if(x.expires<=Date.now()){STATE.values.delete(k);return undefined}return x.v}
function background(m,id,s,e){if(!m||!m.mal_id)return;try{void fetch(POPULATE_URL,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json","User-Agent":UA},body:JSON.stringify({tmdb_id:String(m.tmdb_id||id),imdb_id:m.imdb_id||"",mal_id:m.mal_id,title:m.anime_title||m.title||"",season:Number(s),episode:Number(e),mal_episode:Number(m.mal_episode)})}).catch(()=>{})}catch(e){}}
async function run(id,type,s,e){type=String(type||"tv").toLowerCase();const movie=type==="movie";if(movie){const d=await json(LAZY_URL+"?tmdbId="+encodeURIComponent(id)+"&mediaType=movie",5000),m=valid(d&&d.mapping);if(m){log("MOVIE HIT TMDB="+id+" MAL="+m.mal_id);return m}log("MOVIE MISS TMDB="+id);return null}const lazy=await json(LAZY_URL+"?tmdbId="+encodeURIComponent(id)+"&season="+encodeURIComponent(s)+"&episode="+encodeURIComponent(e),3000),lm=valid(lazy&&lazy.mapping);if(lm){log("LAZY HIT TMDB="+id+" S"+s+"E"+e);return lm}const normal=await json(NORMAL_URL+"?tmdbId="+encodeURIComponent(id)+"&season="+encodeURIComponent(s)+"&episode="+encodeURIComponent(e),7000),nm=valid(normal&&normal.mapping);if(nm){log("NORMAL HIT TMDB="+id+" S"+s+"E"+e);background(nm,id,s,e);return nm}log("MISS TMDB="+id+" S"+s+"E"+e);return null}
async function getMapping(tmdbId,mediaType="tv",season=1,episode=1){const id=String(tmdbId||"").trim(),type=String(mediaType||"tv").toLowerCase(),s=Number(season)||1,e=Number(episode)||1;if(!id)return null;const k=key(id,type,type==="movie"?1:s,type==="movie"?1:e),cached=get(k);if(cached!==undefined)return cached;if(STATE.inflight.has(k))return STATE.inflight.get(k);const p=run(id,type,s,e).then(v=>{save(k,v,type==="movie"?MOVIE_TTL:TTL);return v}).catch(e=>{log("ERROR TMDB="+id+" "+e.message);save(k,null,30000);return null}).finally(()=>STATE.inflight.delete(k));STATE.inflight.set(k,p);return p}
function clearMappingCache(){STATE.values.clear();STATE.inflight.clear()}
module.exports={getMapping,clearMappingCache};
