"use strict";
// ZokoAnime direct stream resolver. Uses its in-page XOR payload format.

const MAPPING_URL="https://anikoto-nuvio.netlify.app/.netlify/functions/anime-lazy-mapping";
const UA="Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/AD1A.240418.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.54 Mobile Safari/537.36";
async function _req(url,opt={},ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opt,headers:{"User-Agent":UA,"Accept":"*/*",...(opt.headers||{})},signal:c.signal})}finally{clearTimeout(t)}}
async function _json(url,opt={},ms=9000){try{const r=await _req(url,opt,ms);if(!r.ok)return null;return await r.json()}catch(e){return null}}
async function _text(url,opt={},ms=9000){try{const r=await _req(url,opt,ms);if(!r.ok)return "";return await r.text()}catch(e){return ""}}
async function _mapping(tmdbId,season,episode){const u=MAPPING_URL+"?tmdb_id="+encodeURIComponent(tmdbId)+"&tmdbId="+encodeURIComponent(tmdbId)+"&season="+encodeURIComponent(season)+"&episode="+encodeURIComponent(episode)+"&pending=1";const d=await _json(u,{},5500);if(!d||!d.ok||!d.mapping)return null;const m=d.mapping,malId=String(m.mal_id||m.malId||"").trim(),malEpisode=Number(m.mal_episode||m.target_episode||0);if(!malId||!Number.isInteger(malEpisode)||malEpisode<1)return null;return {malId,episode:malEpisode,title:String(m.anime_title||m.title||"").trim(),titles:Array.isArray(m.titles)?m.titles.filter(Boolean).map(String):[]}}
async function _anilistId(malId){const q='query($idMal:Int){Media(idMal:$idMal,type:ANIME){id title{english romaji native}}}';const d=await _json("https://graphql.anilist.co",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({query:q,variables:{idMal:Number(malId)}})},7000);const m=d&&d.data&&d.data.Media;return m&&m.id?{id:String(m.id),titles:[m.title.english,m.title.romaji,m.title.native].filter(Boolean)}:null}
function _lang(settings){const x=String(settings&& (settings.language||settings.audio||settings.lang)||"sub").toLowerCase();return x.includes("dub")?"dub":"sub"}
function _unique(a){return [...new Set((a||[]).filter(Boolean))]}
function _decodeAnimeX(u){if(!String(u).includes('/uwu/'))return {url:u,referer:""};try{let tok=String(u).split('/uwu/').pop();tok=tok.replace(/-/g,'+').replace(/_/g,'/');while(tok.length%4)tok+='=';const raw=atob(tok),key='10b06cdc1ca48c9fb0b94af97cc040cf';let s='';for(let i=0;i<raw.length;i++)s+=String.fromCharCode(raw.charCodeAt(i)^key.charCodeAt(i%key.length));const p=s.split('\0');return {url:p[0]||u,referer:p[1]||''}}catch(e){return {url:u,referer:''}}}

const BASE="https://zokoanime.video",KEY="otaku-embed-v1";
function decodeZoko(blob){try{const raw=atob(blob);let s="";for(let i=0;i<raw.length;i++)s+=String.fromCharCode(raw.charCodeAt(i)^KEY.charCodeAt(i%KEY.length));return JSON.parse(s)}catch(e){return null}}
async function resolve(id,episode,lang,key){const page=await _text(`${BASE}/stream/${key}/${encodeURIComponent(id)}/${episode}/${lang}`,{headers:{"Referer":BASE+"/","Accept":"text/html,application/xhtml+xml,*/*"}},9000);const hit=page.match(/window\.__P\s*=\s*["']([^"']+)["']/);return hit?decodeZoko(hit[1]):null}
async function getStreams(tmdbId,mediaType="tv",season=1,episode=1,settings={}){try{if(String(mediaType).toLowerCase()!=="tv")return[];const m=await _mapping(tmdbId,season,episode);if(!m)return[];const lang=_lang(settings);let p=await resolve(m.malId,m.episode,lang,"mal");if(!p){const al=await _anilistId(m.malId);if(al)p=await resolve(al.id,m.episode,lang,"ani")}if(!p||!p.src)return[];const streamHeaders={Referer:BASE+"/","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"};const subs=(p.subtitles||[]).filter(x=>x&&x.src).map(x=>({url:String(x.src),language:String(x.lang||"en"),name:String(x.label||x.lang||"English")}));return [{name:"Zoko",title:"Zoko · "+lang.toUpperCase(),url:p.src,quality:"auto",type:"m3u8",headers:streamHeaders,subtitles:subs,backup:false}]}catch(e){console.log("[Zoko] "+String(e&&e.message||e));return[]}}
module.exports={getStreams};
